### PR TITLE
Namespace creation 

### PR DESCRIPTION
**Pull request by saiyam1814**
#16 fixed

### CODE REVIEW

**Comment by funkypenguin** [comment]
Hey @saiyam1814! Thanks for the PR!

We actually had a considered internal discussion re whether to include a namespace resource in the helm chart, and decided not to, since helm v3 wants to _store_ its secrets in the target namespace. If the target namespace doesn't exist, then helm can't store its secrets, and will error upon installation. Further, it seems to be generally accepted practice with helm v3 that the namespace should be created by the user, since namespaces are cluster-scoped resources, and it may be desirable to run helm with a service account with privileges limited to a single namespace. (I realize that's sort of redundant in the case of Portainer, since we assign our service account cluster-admin privileges anyway)

The conclusion we came to, is that for maximum compatibility between helm, CI/CD, and various implementation strategies, the user should create the namespace themselves, and then deploy _into_ it using helm ;)

Cheers!
D

**Comment by saiyam1814** [comment]
Agree for helm 3 its expected that the user creates the namespace. But since its a file that can directly be used as mentioned in the docs as well, so thought of adding a namespace creation.

**Comment by saiyam1814** [comment]
I believe since these are stand-alone manifests to deploy portainer, so they should be complete.

**Comment by funkypenguin** [comment]
#50 addresses this, since `--create-namespace` [is now supported](https://github.com/roboll/helmfile/issues/891) in Helm v3.2+

**Pull request closed without merging**
