### PR TITLE
Add service annotations field to Helm Chart

### LINKED ISSUE #18: Make service annotations available in Helm Chart
Hey there,

as we're deploying Portainer to AKS using Helm we want to add annotations to the service definition. These are currently not available in the corresponding Helm template. I'm preparing a PR to add the field.

### PR DESCRIPTION
**Pull request by fastexitlane**
fixes #18

### CODE REVIEW

**Comment by funkypenguin** [comment]
Hey @fastexitlane, thanks for the PR! This looks good, the only additions I'd like to request are:

* [ ] Update the [README](https://github.com/portainer/k8s/blob/master/charts/portainer/README.md) to indicate what `service.annotations` is intended to do
* [ ] Bump the chart version in [chart.yaml](https://github.com/portainer/k8s/blob/master/charts/portainer/Chart.yaml#L19) to `1.0.3`, so that CI will issue a new release ;) 

Thanks!
D

**Comment by fastexitlane** [comment]
Hey @funkypenguin, thanks for the feedback. I bumped the Chart version and added a short hint for the `service.annotations` field to the Chart README. Let me know if I should add some more information on that topic (use cases or something like that).

Cheers!

**Comment by funkypenguin** [comment]
Looks good, let's see whether she'll pass the CT validator ;)

**Comment by funkypenguin** [comment]
Lookin' good, thanks @fastexitlane !

**Pull request merged**
