### PR TITLE
Add option to set tolerations 

### LINKED ISSUE #154: Add option to set toleration
Currently, there is no option to set tolerations on the chart. A valid usecase for this, would be the following:

- As a system engineer, I want to run portainer on a dedicated node, with no other pods running on that node.

For this, the nodeSelector can be used to select the node to run portainer on. In order to prevent other pods from scheduling, a taint is applied to the node. However, there is no option to set a toleration, allowing the portainer pod to schedule on the tainted node.

A PR will be provided by us to solve this issue.

### PR DESCRIPTION
**Pull request by mwoudstra**
Closes #154

### CODE REVIEW

**Comment by mwoudstra** [comment]
@samdulam Is there anyone who can review this?

**Comment by samdulam** [comment]
@mwoudstra 
Thanks for raising this. Could you please bump the cart version so the publish workflow doesn't fail?
Change to 1.0.58

**Comment by mwoudstra** [comment]
@samdulam Updated! Thanks!

**Review by samdulam — APPROVED** [review]
LGTM

**Pull request merged**
